# Generated by Django 4.1.4 on 2022-12-21 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DaniRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RestaurantName', models.CharField(max_length=200)),
                ('RestaurantAddreess', models.CharField(max_length=200)),
                ('FoodTypes', models.CharField(max_length=200)),
                ('FoodPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PhoneNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('total_in_cents', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='my_restaurant.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='food_industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='my_restaurant.danirestaurant'),
        ),
    ]
