# Generated by Django 4.1.4 on 2022-12-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0002_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danirestaurant',
            name='PhoneNumber',
            field=models.BigIntegerField(),
        ),
    ]
